call product.add_new_product('HP','Viper Plus','PC',18500000);     
call product.add_new_product('Samsung','ProArt','PC',13990000);
call product.add_new_product('MSI','Phantom','PC',30990000);
call product.add_new_product('LG','Unicorn','PC',25919000);
call product.add_new_product('Kingston','PNY Silver','RAM',890000);
call product.add_new_product('Samsung','Corsair','RAM',1150000);
call product.add_new_product('Seagate','Trident','RAM',2000000);
call product.add_new_product('Sandisk','Beast','RAM',1990000);
call product.add_new_product('Huawei','Dorminator','RAM',500000);
call product.add_new_product('Samsung','Optix','Monitor',7500000);
call product.add_new_product('Xiaomi','Lookthrough','Monitor',3400000);
call product.add_new_product('AKKO','Ocean Star','Keyboard',2000000);
call product.add_new_product('Razer','MonsGeek','Keyboard',1080000);
call product.add_new_product('Asus','ROG','Mouse',300000);
call product.add_new_product('Logitech','Anywhere','Mouse',450000);   
call product.add_new_product('Gigabyte','GeForce','VGA',5000000);   
call product.add_new_product('Asus','Dual 3060','VGA',6000000);     
call product.add_new_product('MSI','Gaming X','VGA',1500000);       
call product.add_new_product('Intel','TUF Gaming','VGA',2000000);   



call product.add_new_general_specs('Blue', 'color','blue','', 'RAM');
call product.add_new_general_specs('Black', 'color','black','', 'RAM');
call product.add_new_general_specs('White', 'color','white','', 'RAM');
call product.add_new_general_specs('Red', 'color','red','', 'RAM');
call product.add_new_general_specs('8GB', 'ram_capacity','8_gb','', 'RAM');
call product.add_new_general_specs('16GB', 'ram_capacity','16_gb','', 'RAM');
call product.add_new_general_specs('32GB', 'ram_capacity','32_gb','', 'RAM');
call product.add_new_general_specs('64GB', 'ram_capacity','64_gb','', 'RAM');
call product.add_new_general_specs('2700MHz', 'clock_speed','2700_mhz','', 'VGA');  
call product.add_new_general_specs('3000MHz', 'clock_speed','3000_mhz','', 'VGA');
call product.add_new_general_specs('3200MHz', 'clock_speed','3200_mhz','', 'VGA');
call product.add_new_general_specs('3600MHz', 'clock_speed','3600_mhz','', 'VGA');
call product.add_new_general_specs('2kg', 'weight','2_kg','', 'VGA');               
call product.add_new_general_specs('3kg', 'weight','3_kg','', 'VGA');
call product.add_new_general_specs('4kg', 'weight','4_kg','', 'VGA');
call product.add_new_general_specs('12GB','memory_capacity','12_gb','', 'VGA');     
call product.add_new_general_specs('16GB','memory_capacity','16_gb','', 'VGA');
call product.add_new_general_specs('24GB','memory_capacity','24_gb','', 'VGA');


call product.add_spec_to_product(17,60);
call product.add_spec_to_product(17,64);
call product.add_spec_to_product(17,68);
call product.add_spec_to_product(17,69);
call product.add_spec_to_product(17,73);
call product.add_spec_to_product(18,61);
call product.add_spec_to_product(18,65);
call product.add_spec_to_product(18,66);
call product.add_spec_to_product(18,70);
call product.add_spec_to_product(18,71);
call product.add_spec_to_product(19,62);
call product.add_spec_to_product(19,64);
call product.add_spec_to_product(19,67);
call product.add_spec_to_product(19,69);
call product.add_spec_to_product(19,72);
call product.add_spec_to_product(20,59);
call product.add_spec_to_product(20,63);
call product.add_spec_to_product(20,67);
call product.add_spec_to_product(20,70);
call product.add_spec_to_product(20,74);
call product.add_spec_to_product(21,75);
call product.add_spec_to_product(21,79);
call product.add_spec_to_product(22,76);
call product.add_spec_to_product(22,80);
call product.add_spec_to_product(23,77);
call product.add_spec_to_product(23,81);
call product.add_spec_to_product(24,78);
call product.add_spec_to_product(24,82);
call product.add_spec_to_product(25,75);
call product.add_spec_to_product(25,81);
call product.add_spec_to_product(26,37);
call product.add_spec_to_product(26,40);
call product.add_spec_to_product(27,38);
call product.add_spec_to_product(27,41);
call product.add_spec_to_product(28,42);
call product.add_spec_to_product(28,45);
call product.add_spec_to_product(28,47);
call product.add_spec_to_product(28,49);
call product.add_spec_to_product(29,43);
call product.add_spec_to_product(29,46);
call product.add_spec_to_product(29,48);
call product.add_spec_to_product(29,50);
call product.add_spec_to_product(30,52);
call product.add_spec_to_product(30,57);
call product.add_spec_to_product(30,55);
call product.add_spec_to_product(31,53);
call product.add_spec_to_product(31,58);
call product.add_spec_to_product(31,56);
call product.add_spec_to_product(32,83);
call product.add_spec_to_product(32,87);
call product.add_spec_to_product(32,90);
call product.add_spec_to_product(33,84);
call product.add_spec_to_product(33,88);
call product.add_spec_to_product(33,91);
call product.add_spec_to_product(34,85);
call product.add_spec_to_product(34,89);
call product.add_spec_to_product(34,92);
call product.add_spec_to_product(35,86);
call product.add_spec_to_product(35,87);
call product.add_spec_to_product(35,91);



