call product.add_new_product('Sony','GVN Minion','PC',20990000);
call product.add_new_product('HP','Viper Plus','PC',18500000);
call product.add_new_product('Samsung','ProArt','PC',13990000);
call product.add_new_product('MSI','Phantom','PC',30990000);
call product.add_new_product('LG','Unicorn','PC',25919000);
call product.add_new_product('Kingston','PNY Silver','RAM',890000);
call product.add_new_product('Samsung','Corsair','RAM',1150000);
call product.add_new_product('Seagate','Trident','RAM',2000000);
call product.add_new_product('Sandisk','Beast','RAM',1990000);
call product.add_new_product('Huawei','Dorminator','RAM',500000);
call product.add_new_product('Samsung','GalaxyA6','Monitor',7500000);
call product.add_new_product('Xiaomi','GalaxyA6','Monitor',3400000);
call product.add_new_product('AKKO','Ocean Star','Keyboard',2000000);
call product.add_new_product('Razer','MonsGeek','Keyboard',1080000);
call product.add_new_product('Asus','ROG','Mouse',300000);
call product.add_new_product('Logitech','Anywhere','Mouse',450000);


call product.add_new_general_specs('Windows 10', 'os','win10','Windows 10 Home', 'PC');
call product.add_new_general_specs('Windows 10', 'os','win10','Windows 10 Pro', 'PC');
call product.add_new_general_specs('Windows 11', 'os','win11','Windows 11 Home', 'PC');
call product.add_new_general_specs('Windows 11', 'os','win11','Windows 11 Pro', 'PC');
call product.add_new_general_specs('4GB', 'ram_capacity','4_gb','', 'PC');
call product.add_new_general_specs('8GB', 'ram_capacity','8_gb','', 'PC');
call product.add_new_general_specs('16GB', 'ram_capacity','16_gb','', 'PC');
call product.add_new_general_specs('1920 x 1080', 'display_resolution','1920_1080','Full HD', 'PC');
call product.add_new_general_specs('2560 x 1440', 'display_resolution','2560_1440','Quad HD', 'PC');
call product.add_new_general_specs('3840 x 2160', 'display_resolution','3840_2160','4K', 'PC');
call product.add_new_general_specs('15.6"', 'display_size','15_6_inch','15.6 inches', 'PC');
call product.add_new_general_specs('17.3"', 'display_size','17_3_inch','17.3 inches', 'PC');
call product.add_new_general_specs('Intel® Core™ i5', 'cpu_model','i5_11300','i5 - 11300, 8C/16T, 2.50GHz up to 4.40GHz, 20MB Cache, 65W', 'PC');
call product.add_new_general_specs('Intel® Core™ i3', 'cpu_model','i3_11100','i3 - 11100, 4C/8T, 3.10GHz up to 4.40GHz, 8MB Cache, 65W', 'PC');
call product.add_new_general_specs('Intel® Core™ i9', 'cpu_model','i9_11900','i9 - 11900, 16C/32T, 2.50GHz up to 5.30GHz, 40MB Cache, 125W', 'PC');
call product.add_new_general_specs('Intel® Core™ i7', 'cpu_model','i7_11700','i7 - 11700, 8C/16T, 2.50GHz up to 5.00GHz, 32MB Cache, 65W', 'PC');
call product.add_new_general_specs('Blue', 'color','blue','', 'RAM');
call product.add_new_general_specs('Black', 'color','black','', 'RAM');
call product.add_new_general_specs('White', 'color','white','', 'RAM');
call product.add_new_general_specs('Red', 'color','red','', 'RAM');
call product.add_new_general_specs('8GB', 'ram_capacity','8_gb','', 'RAM');
call product.add_new_general_specs('16GB', 'ram_capacity','16_gb','', 'RAM');
call product.add_new_general_specs('32GB', 'ram_capacity','32_gb','', 'RAM');
call product.add_new_general_specs('64GB', 'ram_capacity','64_gb','', 'RAM');


call product.add_spec_to_product(17,59);
call product.add_spec_to_product(17,63);
call product.add_spec_to_product(17,67);
call product.add_spec_to_product(17,70);
call product.add_spec_to_product(17,74);
call product.add_spec_to_product(18,60);
call product.add_spec_to_product(18,64);
call product.add_spec_to_product(18,68);
call product.add_spec_to_product(18,69);
call product.add_spec_to_product(18,73);
call product.add_spec_to_product(19,61);
call product.add_spec_to_product(19,65);
call product.add_spec_to_product(19,66);
call product.add_spec_to_product(19,70);
call product.add_spec_to_product(19,71);
call product.add_spec_to_product(20,62);
call product.add_spec_to_product(20,64);
call product.add_spec_to_product(20,67);
call product.add_spec_to_product(20,69);
call product.add_spec_to_product(20,72);
call product.add_spec_to_product(21,59);
call product.add_spec_to_product(21,63);
call product.add_spec_to_product(21,67);
call product.add_spec_to_product(21,70);
call product.add_spec_to_product(21,74);
call product.add_spec_to_product(22,75);
call product.add_spec_to_product(22,79);
call product.add_spec_to_product(23,76);
call product.add_spec_to_product(23,80);
call product.add_spec_to_product(24,77);
call product.add_spec_to_product(24,81);
call product.add_spec_to_product(25,78);
call product.add_spec_to_product(25,82);
call product.add_spec_to_product(26,75);
call product.add_spec_to_product(26,81);
call product.add_spec_to_product(27,37);
call product.add_spec_to_product(27,40);
call product.add_spec_to_product(28,38);
call product.add_spec_to_product(28,41);
call product.add_spec_to_product(29,42);
call product.add_spec_to_product(29,45);
call product.add_spec_to_product(29,47);
call product.add_spec_to_product(29,49);
call product.add_spec_to_product(30,43);
call product.add_spec_to_product(30,46);
call product.add_spec_to_product(30,48);
call product.add_spec_to_product(30,50);
call product.add_spec_to_product(31,52);
call product.add_spec_to_product(31,57);
call product.add_spec_to_product(31,55);
call product.add_spec_to_product(32,53);
call product.add_spec_to_product(32,58);
call product.add_spec_to_product(32,56);




